name: Firebase Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Install functions dependencies
        run: |
          cd functions
          npm ci


      - name: Deploy to Firebase
        env:
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: firebase deploy --only functions,hosting --project ${{ env.FIREBASE_PROJECT }}

      - name: Post-deploy smoke tests
        run: |
          set -euo pipefail

          curl -sSf https://aispace.bakhmaro.co/api/version | tee /tmp/version.json
          test -s /tmp/version.json

          curl -sSf https://aispace.bakhmaro.co/api/ai/health | tee /tmp/health.json
          test -s /tmp/health.json

          set +o pipefail
          tmp_sse=$(mktemp)
          curl -NsSf https://aispace.bakhmaro.co/api/console/events --max-time 20 | head -n 5 | tee "$tmp_sse"
          curl_status=${PIPESTATUS[0]}
          set -o pipefail
          if [ "$curl_status" -ne 0 ]; then
            echo "SSE smoke test failed" >&2
            cat "$tmp_sse" >&2 || true
            exit 1
          fi
          test -s "$tmp_sse"
