name: Firebase Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Type-check
        run: npm run type-check

      - name: Build app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Install functions dependencies
        run: |
          cd functions
          npm ci

      - name: Deploy to Firebase
        env:
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: firebase deploy --only functions,hosting --project ${{ env.FIREBASE_PROJECT }}

      - name: Smoke check — API version
        run: curl -sSf https://aispace.bakhmaro.co/api/version

      - name: Smoke check — AI health
        run: curl -sSf https://aispace.bakhmaro.co/api/ai/health

      - name: Smoke check — Console events SSE
        run: |
          set -euo pipefail
          first_line=""
          while IFS= read -r line; do
            first_line="$line"
            break
          done < <(curl -sSNf --max-time 5 https://aispace.bakhmaro.co/api/console/events)

          if [ -z "$first_line" ]; then
            echo "No SSE data received" >&2
            exit 1
          fi

          printf '%s\n' "$first_line"

